"""empty message

Revision ID: 240b39adc7e5
Revises: 
Create Date: 2018-02-01 11:42:22.030780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240b39adc7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses') as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), default = 0))
        batch_op.alter_column('votes', nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses') as batch_op:
        batch_op.drop_column('votes')
    # ### end Alembic commands ###
