"""empty message

Revision ID: 514139b859bf
Revises: 
Create Date: 2018-02-01 18:07:09.027967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514139b859bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('votes', sa.Integer(), default = 0))
    op.execute('UPDATE responses SET votes=0 WHERE votes IS NULL')
    op.alter_column('responses', 'votes', nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'votes')
    # ### end Alembic commands ###
